=== nmcl/sandbox/Arjuna-XTS-EA/WSCF/xml/WSCF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Thomas Novellino (Hewlett Packard Co.) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="coordinator-name" type="xsd:anyURI">
		<xsd:annotation>
			<xsd:documentation>The unique name for this type of coordinator</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="response">
		<xsd:annotation>
			<xsd:documentation>The response that may be returned upon receipt of a specific notification</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notification">
		<xsd:annotation>
			<xsd:documentation>The notification message that may be sent</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string"/>
				<xsd:element ref="response" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="coordination-type">
		<xsd:annotation>
			<xsd:documentation>The type of the coordination protocol supported</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="coordinator-name" minOccurs="0"/>
				<xsd:element ref="notification" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="generic" type="xsd:boolean" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== nmcl/sandbox/Arjuna-XTS-EA/WSCF/build/classes/com/arjuna/mwlabs/wscf/model/as/coordinator/arjunacore/ArjunaCoreHLS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Thomas Novellino Version 4.0 (Hewlett Packard Co.) -->
<!--Sample XML file generated by XML Spy v4.0 U (http://www.xmlspy.com)-->
<coordination-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\mlittle\Desktop\standards work\WS architecture\WSCF\0.8.2\xml\WSCF.xsd">
	<coordinator-type>urn:generic:tx-two-phase-commit</coordinator-type>
	<generic>true</generic>
	<notification>
		<name>BeforeCompletion</name>
	</notification>
	<notification>
		<name>AfterCompletion</name>
	</notification>
	<notification>
		<name>ForgetHeuristic</name>
	</notification>
	<notification>
		<name>NestedCancel</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>NestedConfirm</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>NestedOnePhaseCommit</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>NestedPrepare</name>
		<response>
			<name>VoteCancel</name>
			<name>VoteConfirm</name>
			<name>VoteReadOnly</name>
		</response>
	</notification>
	<notification>
		<name>TopLevelCancel</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>TopLevelConfirm</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>TopLevelOnePhaseCommit</name>
		<response>
			<name>CoordinationOutcome</name>
		</response>
	</notification>
	<notification>
		<name>NestedPrepare</name>
		<response>
			<name>VoteCancel</name>
			<name>VoteConfirm</name>
			<name>VoteReadOnly</name>
		</response>
	</notification>
</coordination-type>

=== nmcl/sandbox/Arjuna-XTS-EA/WSCF/xml/WSBAHLS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Thomas Novellino Version 4.0 (Hewlett Packard Co.) -->
<!--Sample XML file generated by XML Spy v4.0 U (http://www.xmlspy.com)-->
<coordination-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\mlittle\Desktop\standards work\WS architecture\WSCF\0.8.2\xml\WSCF.xsd">
	<coordinator-type>urn:generic:tx-jta</coordinator-type>
	<notification>
		<name>XACommit</name>
	</notification>
	<notification>
		<name>XAStart</name>
	</notification>
	<notification>
		<name>XAEnd</name>
	</notification>
	<notification>
		<name>XAForget</name>
	</notification>
	<notification>
		<name>XAPrepare</name>
		<response>
			<name>XAOutcome</name>
		</response>
	</notification>
	<notification>
		<name>XARecover</name>
		<response>
			<name>XIDList</name>
		</response>
	</notification>
</coordination-type>

=== nmcl/sandbox/Arjuna-XTS-EA/WSCF/xml/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Thomas Novellino Version 4.0 (Hewlett Packard Co.) -->
<!--Sample XML file generated by XML Spy v4.0 U (http://www.xmlspy.com)-->
<coordination-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\mlittle\Desktop\standards work\WS architecture\WSCF\0.8.2\xml\WSCF.xsd">
	<coordinator-type>urn:two-phase</coordinator-type>
	<notification>
		<name>prepare</name>
		<response>
			<name>confirm</name>
			<name>cancel</name>
			<name>readonly</name>
		</response>
	</notification>
	<notification>
		<name>confirm</name>
		<response>
			<name>confirmed</name>
			<name>cancelled</name>
		</response>
	</notification>
	<notification>
		<name>cancel</name>
		<response>
			<name>cancelled</name>
			<name>confirmed</name>
		</response>
	</notification>
</coordination-type>
